<!--Wrapper Start-->
<!--
<script type="text/javascript" >
	$(function(){
		
		var btnUpload=$('#upload');
		var status=$('#status');
		new AjaxUpload(btnUpload, {
			action: 'upload/do_upload',
			name: 'postImage',
			data: {field_name:'postImage',folder_name:'Sub_Category'},
			onSubmit: function(file, ext){
				 if (! (ext && /^(jpg|png|jpeg|gif)$/.test(ext))){ 
                    // extension is not allowed 
					status.text('Only JPG, PNG or GIF files are allowed');
					return false;
				}
				status.text('Uploading...');
			},
			onComplete: function(file, response){
				//On completion clear the status
				status.text('');
				var output = $.parseJSON(response);
				if(output.status){

					var previewHTML = '<div class="user-thmb-block"><div class="user-profile-thmb" id="sub_category_image"></div><div class="change-pro-pic"></div></div>';					
					$("#files").html(previewHTML);
					$("#file_upload_id").val(output.data.file_upload_id);
					showImage(output.data.file_upload_id,'140','140','show_image');
				}else{
					$("#files").html(output.data);
				}				
			}
		});
	});
		
	</script>-->

<div id="wrapper">
<div class="breadcrumb"></div>
    <div class="container">
        <div class="maintitle">
            <h1>Add New Sub Category</h1>
            <div class="btnbox"> <?php echo anchor('home/displayposttypelist' , '<span class="back-icon"></span>Back to Post Type List' , 'class="btnorange"') ?> </div>
        </div>
        <div class="clear"></div>
		<?php echo form_open('home/addsubcategory');?>
        
        <table border="0" cellspacing="0" cellpadding="0" class="tbldtl add-new-user">
            <tr>
                <td>Sub Category Name:</td>
                <td><div class="field">
                       <input type="text" id="sub_category_name" name="sub_category_name" class="inputmain" value="" maxlength="60" />
                    </div>
					<span class="error"><?php echo form_error('sub_category_name'); ?>	</span>
				</td>
            </tr>
            <tr>
                <td>Mandatory Capsule:</td>
                <td><div class="field">
				 <ul>
				  <?php foreach($capsule_list as $row){ ?>
					<li> <?php
				            $checkbox_data = array('name'=>"check[".$row['capsule_type_id']."]",'class' => "u");
							 if($row['capsule_type_id'] == 5)
								{
						            $checkbox_data = array('name'=>"check[".$row['capsule_type_id']."]",
														   'class' => "u",
														   'checked'=>"checked",
														   'disabled' => "disabled"
														   );
								}

							echo form_checkbox($checkbox_data)." ".$row['name']; ?> 
					</li>
				  <?php }?>
				  </ul>


                      <!-- checkbox and name of capsule type generated by database on run time -->
                    </div></td>
            </tr>
            <tr>
                <td>Status :</td>
                <td><div class="field">
				        <select  id="is_active" name="is_active" >
							 <option id="active" value="1" selected> Active </option>
							 <option id="deactive" value="0">De-Active</option>
                     </select>
                    </div>
				</td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td><input type="Submit" name="add_user" id="add_user" class="btnorange" value="Add New Sub Category" />
                    <input type="Submit" class="btngrey" value="Cancel" /></td>
            </tr>
        </table>
        <?php echo form_close(); ?>
    </div>
    <div class="clear"></div>
</div>
<!--Wrapper End--> 