<div id="wrapper">
	<div class="left-content-main"> <?php echo $sidebar; ?></div> 
	<div class="rightmain">
        <div class="breadcrumb"> <span class="arrowleft"></span>
            <ul>
				<li><?php echo anchor('','Home');?></li>
              	<li><a href="javascript:void(0);" class="active">Terms of Service</a></li>
            </ul>
        </div>
        <div class="rightinner">
        	<div class="contentpanel">
        		<div class="titlesec"><h1 class="orangetitle-f20">Terms of Service</h1>
                </div>     	 	
<p>InkSmash is a service of T&F Ventures LLC. (collectively referred to as "InkSmash"), owning and operating the www.inksmash.com Internet Site (the "Site"), that offers you a free publishing platform for the purpose of publishing original content and materials in any field of interest, whether in written, visual, audio, video or any other technological form supported by InkSmash (the "Original Content" or the "Materials"), under and subject to the terms and conditions set forth in this Agreement.</p>
<p><span class="sub-title">Acceptance of Terms</span>The actual use of the site shall be construed as and attest your unconditional, unlimited and unreserved acceptance of the terms and conditions set forth herein, and shall be considered as a binding agreement between you and InkSmash and an undertaking on your behalf to comply with the terms and conditions set forth herein (above and hereinafter referred to as the "Agreement").</p>
<p><span class="sub-title">Registration Form</span>In order to be able to publish any Original Content on the Site you may be required to complete a simple registration process and form, in which you are required to submit your valid email address and certain personal details.</p>
<p><span class="sub-title">Content</span>You hereby understand, acknowledge, undertake, represent and warrant that any Original Content sent by you with the intention it be published on the Site shall comply with the following requirements:</p>
<ul>
<li>be your original work; </li>
<li>shall have not been previously publicly published, in whole or in part, on the internet or any other media </li>
<li>shall not contain any content of any kind whatsoever that is libelous, illegal or infringes any third parties' copyrights; </li>
<li>if any third parties' copyrights are included in the Original Content, the express, unrestricted and unlimited permission of such copyrights owner for the use of such copyrighted materials has been obtained prior to submitting the Original Content; </li>
<li>shall not contain any derogatory, offensive, unlawful, harmful, threatening, vulgar, profane, abusive, harassing, obscene, pornographic, defamatory or tortuous content</li>
</ul>
<p><span class="sub-title">Rights Granted</span>By submitting your Original Content for publication on the Site, you hereby irrevocably and unconditionally grant InkSmash an irrevocable, perpetual, unlimited free of charge and exclusive right to publish the Original Content on the Site and/or on other Internet Sites the Original Content shall be referred to by InkSmash (hereinafter also referred to as the "Site"), as InkSmash shall deem suitable under the terms and conditions of this Agreement, as well as allow users of the Site to view and further use the Original Content, free of charge, for any such purpose permitted by InkSmash, provided such use shall not be for profit generating purposes. Without derogating from the above, InkSmash shall be entitled to edit, delete, cutback, rephrase, reproduce, copy, translate, merge, add, use and make use of the Materials, in whole or in part, in any way or manner and at any time, as InkSmash shall deem appropriate in its sole discretion.</p>
<p><span class="sub-title">Author's Rights</span>You shall continue to retain all authorship and copyrights to the Materials submitted for publication through the website.</p>
<p><span class="sub-title">Publishing Period</span>For avoidance of any doubt, InkSmash does not undertake to and shall not be obligated to publish any Materials submitted for publication on the Site, nor does InkSmash undertake to or shall be obligated to publish any of the Materials on the Site for any minimum or certain period of time.</p>
<p><span class="sub-title">Advertising &amp; Links</span>You hereby understand, acknowledge and agree that the pages on the Site will contain advertising and promotional materials as well as links to other sites (a "Linked Site"), as shall be determined by InkSmash in its sole discretion. InkSmash is not and shall not be responsible for any content, services, products or goods which appear and/or are advertised on any Linked Site, nor for the availability and functionality of such ("Linked Sites"). InkSmash reserves the rights to remove, in its sole and absolute discretion, any and all links which may appear in any Original Content. Without derogating from the above, InkSmash will remove from the Materials any links that link/refer to advertisements or any other content of promotional/advertising nature.</p>
<p>Remuneration. The publishing of Original Content submitted by you on the Site, shall entitled you to receive a certain number of Google Adsense ad impressions, as provided herein:</p>
<ul>
<li>InkSmash will provide Google Adsense ad impressions and Amazon Associates Program links in the amount of 70 % of the net amounts it shall actually receive from Google Adsense and Amazon Associates advertising on the page on which the Original Content appears and which are relatively attributed to your Original Content, as shall be determined by InkSmash (the "Commission"); Changes or differentiations in the rate of the Commission may be made by InkSmash in its sole and absolute discretion. </li>
<li>Commissions accumulated through the Google Adsense program and Amazon Associates Affiliate Program are subject to the terms and services of the Google Adsense program and Amazon Associates Affiliate Program.</li>
<li>InkSmash shall not be liable in any way or manner for Google Adsense or Amazon Associates Affiliate payments. All inquiries regarding Google Adsense or Amazon Associate Affiliates payments should be taken up with the Google Adsense and Amazon Associate program.</li>
<li>You shall be responsible for any and all personal taxes due and payable with respect to payment of Commissions you shall receive from Google Adsense or Amazon Associates Program.</li>
</ul>
<p><span class="sub-title">Privacy Policy</span>Personal details provided by you in the Registration Form, shall be kept in confidence, provided that such information may be used by InkSmash for the following purposes (i) if required to be provided under any applicable laws; (ii) internal uses and future communication.</p>
<p><span class="sub-title">Anti-Spam/Junk Mail Policy</span>You undertake, represent and warrant not sending any emails, messages or otherwise communicate with any other users of the Site, which is not wanted or requested by such users. Bulk email messages that will be sent to a group of people who have no desire to receive such messages are forbidden.</p>
<p><span class="sub-title">Fraudulent Use</span>You undertake, represent and warrant not to, directly or indirectly, by yourself or through any third party, generate in any way or manner, by use of any means of technology, software or otherwise, any increased, artificial or false traffic, usage, viewing, or entrances to any Original Content, advertisements, banners, or other content and materials of any kind in order to, whether for the purpose of increasing your Commission payments or any other purpose.</p>
<p><span class="sub-title">Operation of the Site</span>InkSmash reserves the right to suspend and/or modify the operation of the Site and/or to discontinue or cease, temporarily or permanently the operation of the Site, as it shall deem necessary in its sole discretion. No prior notice shall be required to be given by InkSmash with respect to any of the above mentioned events and you shall have no claim whatsoever against InkSmash or any of its directors, officers or employees upon such action. The suspension, discontinuation or ceasing of the Site's activity shall not affect your right to payment of Commissions due with respect to such period before the discontinuation of the operation of the site.</p>
<p><span class="sub-title">Termination of Rights</span>If InkSmash shall be in the opinion that you have not complied with the terms and conditions of this Agreement, in whole or in part, InkSmash shall be entitled to terminate your right to submit and/or publish Original Content on the Site, and to cancel any registration of yours to the Site. Upon the termination of your rights notice shall be sent to you by InkSmash.</p>
<p><span class="sub-title">Disclaimer</span> The use of the site is at your own risk.  InkSmash makes no representations or warranties of any kind, express or implied as the the operation of the site, its contents, any materials or information published, advertised, offered or ortherwise made available on the site.</p>
<p><span class="sub-title">Limitation of Liability</span>To the fullest extent permitted by the applicable law, InkSmash and any of its shareholders, directors, officers or employees shall not be liable for any damages, losses or expenses, direct or indirect, sustained or suffered by you by or as a result of the use of the Site or the Original Content, even where notice of the possibility of incurring such damages, losses or expenses was given.</p>
<p><span class="sub-title">Indemnification</span>You hereby agree to fully indemnify, defend and hold InkSmash, its directors, officers, employees and consultants harmless, immediately on demand, from and against any and all claims, liabilities, damages, losses, costs, and expenses, arising out of your use of the Site and the breach of any of the provisions of this Agreement by you.</p>
<p><span class="sub-title">Entire Agreement</span>The terms and conditions of this Agreement shall constitute the entire agreement with respect to your use of the site, whether your Original Content is submitted and published or not. InkSmash may change and/or modify this Agreement, and any term and condition thereof, in its sole and absolute discretion, without being required to provide any prior notice of any such change and/or modifications.</p>

<p><span class="sub-title">Absence of Third Party Beneficiaries</span> No provisions of this Agreement, whether expressed or implied, are intended or shall be construed as conferring upon or giving any third party any rights, remedies or other benefits of any kind whatsoever.</p>

<p><span class="sub-title">Notices</span>Any notices to be sent to you by InkSmash shall be sent to the email address supplied in the registration form, and shall be deemed to have been received within 24 hours.</p>
                
            </div>
        </div>
    </div>
	<div class="clear"></div>
</div>